[package]
name = "async_once_cell"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

[features]
parking_lot = ["tokio/parking_lot"]

[dependencies]
once_cell = "1.5"
tokio = { version = "1", features = ["sync"] }
